Repository pluxml/PluXml, pull requests merged in 2022-11, with the labels that each got.

#567 lang: Occitan
  core/lang/oc/admin.php
Labels: bug

#566 Filtre la valeur pour PLX_CONFIG_PATH dans plxAdmin::editConfiguration()
  core/lib/class.plx.admin.php
Labels: security

#542 Permettre une liste de messages dans les notifications
  core/lib/class.plx.msg.php
Labels: changes
